const ROOM_TYPES = ['normal', 'training', 'vip'];
const BOOKING_PURPOSES = ['见客', '招募', '培训', '讲座', '会议', '其他'];
const DEFAULT_BOOKING_PERMISSIONS = ['normal'];
const DEFAULT_DAILY_BOOKING_LIMIT_MINUTES = 180;
const MAX_BOOKING_DAYS = 365;
const BOOKING_START_MINUTES = 8 * 60;
const BOOKING_END_MINUTES = 20 * 60;
const BOOKING_SLOT_MINUTES = 30;

module.exports = {
  ROOM_TYPES,
  BOOKING_PURPOSES,
  DEFAULT_BOOKING_PERMISSIONS,
  DEFAULT_DAILY_BOOKING_LIMIT_MINUTES,
  BOOKING_START_MINUTES,
  BOOKING_END_MINUTES,
  BOOKING_SLOT_MINUTES,
  MAX_BOOKING_DAYS
};
